### PR TITLE
feat: rm env will rm pod and service

### PR DESCRIPTION
**Pull request by kemingy**
Signed-off-by: Keming <kemingyang@tensorchord.ai>

* related to https://github.com/tensorchord/envd/pull/1096

### CODE REVIEW

**Review by gaocegege — APPROVED** [review]
/LGTM

**Comment by gaocegege** [comment]
Please fix the build issues

**Comment by kemingy** [comment]
What happened to the go swag? I didn't change anything related to the swag comments or the interface.

**Comment by gaocegege** [comment]
You need to run `make swag` to regenerate the doc. Then commit it to git.

**Comment by kemingy** [comment]
CI failed because golangci-lint takes too long:
* https://github.com/golangci/golangci-lint-action/issues/297

**Pull request merged**
