### PR TITLE
feat: Support image pull secret

### LINKED ISSUE #81: feat(image): Support image registry auth
## Description

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by gaocegege**
Close #81 

Added a new CLI flag image-pull-secret-name and a helm config server.imagePullSecret.

Signed-off-by: Ce Gao <cegao@tensorchord.ai>

### CODE REVIEW

**Comment by gaocegege** [comment]
I will add the doc for the feature after it is merged.

**Comment by VoVAllen** [comment]
Is it possible to depend on a configMap (with certain name?) instead of configuring inside the cli? Or any other non-intrusive way?

**Comment by VoVAllen** [comment]
Is it possible to depend on a configMap (with a certain name?) instead of configuring inside the cli? Or any other non-intrusive way?

**Comment by gaocegege** [comment]
> 
Is it possible to depend on a configMap (with certain name?) instead of configuring inside the cli? Or any other non-intrusive way?

Prefer in CLI argument since we will support remote machine in the future. Let's keep it simple

**Review by VoVAllen — APPROVED** [review]
Is it common for users to rotate the image pull secret? However, we can implement this in the future. 

Current implementation lgtm

**Pull request merged**
