### PR TITLE
chore: go mod tidy to generate API doc in CI

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <cegao@tensorchord.ai>

### CODE REVIEW

**Comment by Xuanwo** [comment]
typo in PR title.

**Comment by gaocegege** [comment]
PTAL

**Review by kemingy — APPROVED** [review]
/lgtm

**Comment by kemingy** [comment]
It seems the tide bot doesn't have a merge pool.

I'm going to merge it manually.

**Pull request merged**
