### PR TITLE
chore: Update default version in chart

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <cegao@tensorchord.ai>

### CODE REVIEW

**Review by VoVAllen — APPROVED** [review]
6/lgtm

**Comment by kemingy** [comment]
Remember to update the version in `cmd/envd-server/main.go`

**Comment by kemingy** [comment]
> > Remember to update the version in `cmd/envd-server/main.go`
> 
> It should be updated by goreleaser. We do not need to update it manually.

I thought the swag comments needed to be modified manually.

**Comment by gaocegege** [comment]
I already run `make swag`. The CI will fail if there is outdated API doc.

**Pull request merged**
